# Build and autotest script for PX4 Firmware
# http://travis-ci.org

language: cpp

before_script:
  - sudo apt-get update -q
# Travis specific tools
  - sudo apt-get install s3cmd grep zip mailutils
# General toolchain dependencies
  - sudo apt-get install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386
  - sudo apt-get install python-serial python-argparse
  - sudo apt-get install flex bison libncurses5-dev autoconf texinfo build-essential libtool zlib1g-dev genromfs git wget
  - pushd .
  - cd ~
  - wget https://launchpadlibrarian.net/174121628/gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2
  - tar -jxf gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2
  - exportline="export PATH=$HOME/gcc-arm-none-eabi-4_7-2014q2/bin:\$PATH"
  - if grep -Fxq "$exportline" ~/.profile; then echo nothing to do ; else echo $exportline >> ~/.profile; fi
  - . ~/.profile
  - popd

git:
  depth: 500

script:
  - arm-none-eabi-gcc --version
  - cd nuttx/tools
  - ./configure.sh px4fmu-v2_upstream/nsh
  - cd ..
  - make
